In [1]:
!pip install mglearn
import os
import mglearn
import numpy as np
import pandas as pd
# The file has no headers naming the columns, so we pass header=None
# and provide the column names explicitly in "names"
adult_path = os.path.join(mglearn.datasets.DATA_PATH, "adult.data")
data = pd.read_csv(
    adult_path, header=None, index_col=False,
    names=['age', 'workclass', 'fnlwgt', 'education',  'education-num',
           'marital-status', 'occupation', 'relationship', 'race', 'gender',
           'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
           'income'])
# For illustration purposes, we only select some of the columns
data = data[['age', 'workclass', 'education', 'gender', 'hours-per-week',
             'occupation', 'income']]
# IPython.display allows nice output formatting within the Jupyter notebook
display(data.head())

Collecting mglearn
  Downloading mglearn-0.2.0-py2.py3-none-any.whl.metadata (628 bytes)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from mglearn) (2.0.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.11/dist-packages (from mglearn) (3.10.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/dist-packages (from mglearn) (1.6.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from mglearn) (2.2.2)
Requirement already satisfied: pillow in /usr/local/lib/python3.11/dist-packages (from mglearn) (11.1.0)
Requirement already satisfied: cycler in /usr/local/lib/python3.11/dist-packages (from mglearn) (0.12.1)
Requirement already satisfied: imageio in /usr/local/lib/python3.11/dist-packages (from mglearn) (2.37.0)
Requirement already satisfied: joblib in /usr/local/lib/python3.11/dist-packages (from mglearn) (1.4.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->mglearn) (1.3.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->mglearn) (4.57.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->mglearn) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->mglearn) (24.2)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->mglearn) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib->mglearn) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->mglearn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->mglearn) (2025.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->mglearn) (1.14.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->mglearn) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib->mglearn) (1.17.0)
Downloading mglearn-0.2.0-py2.py3-none-any.whl (581 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 581.4/581.4 kB 7.1 MB/s eta 0:00:00
Installing collected packages: mglearn
Successfully installed mglearn-0.2.0

,age,workclass,education,gender,hours-per-week,occupation,income
0,39,State-gov,Bachelors,Male,40,Adm-clerical,<=50K
1,50,Self-emp-not-inc,Bachelors,Male,13,Exec-managerial,<=50K
2,38,Private,HS-grad,Male,40,Handlers-cleaners,<=50K
3,53,Private,11th,Male,40,Handlers-cleaners,<=50K
4,28,Private,Bachelors,Female,40,Prof-specialty,<=50K

In [2]:
#We have categorical variable so we need to either do get dummies or one hot encoding

data_dummies=pd.get_dummies(data)
data_dummies

,age,hours-per-week,workclass_ ?,workclass_ Federal-gov,workclass_ Local-gov,workclass_ Never-worked,workclass_ Private,workclass_ Self-emp-inc,workclass_ Self-emp-not-inc,workclass_ State-gov,...,occupation_ Machine-op-inspct,occupation_ Other-service,occupation_ Priv-house-serv,occupation_ Prof-specialty,occupation_ Protective-serv,occupation_ Sales,occupation_ Tech-support,occupation_ Transport-moving,income_ <=50K,income_ >50K
0,39,40,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,True,False
1,50,13,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
2,38,40,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,True,False
3,53,40,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,True,False
4,28,40,False,False,False,False,True,False,False,False,...,False,False,False,True,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,38,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,True,False,True,False
32557,40,40,False,False,False,False,True,False,False,False,...,True,False,False,False,False,False,False,False,False,True
32558,58,40,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,True,False
32559,22,20,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,True,False
32560,52,40,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,True

In [3]:

print(data_dummies.columns)

Index(['age', 'hours-per-week', 'workclass_ ?', 'workclass_ Federal-gov',
       'workclass_ Local-gov', 'workclass_ Never-worked', 'workclass_ Private',
       'workclass_ Self-emp-inc', 'workclass_ Self-emp-not-inc',
       'workclass_ State-gov', 'workclass_ Without-pay', 'education_ 10th',
       'education_ 11th', 'education_ 12th', 'education_ 1st-4th',
       'education_ 5th-6th', 'education_ 7th-8th', 'education_ 9th',
       'education_ Assoc-acdm', 'education_ Assoc-voc', 'education_ Bachelors',
       'education_ Doctorate', 'education_ HS-grad', 'education_ Masters',
       'education_ Preschool', 'education_ Prof-school',
       'education_ Some-college', 'gender_ Female', 'gender_ Male',
       'occupation_ ?', 'occupation_ Adm-clerical', 'occupation_ Armed-Forces',
       'occupation_ Craft-repair', 'occupation_ Exec-managerial',
       'occupation_ Farming-fishing', 'occupation_ Handlers-cleaners',
       'occupation_ Machine-op-inspct', 'occupation_ Other-service',
       'occupation_ Priv-house-serv', 'occupation_ Prof-specialty',
       'occupation_ Protective-serv', 'occupation_ Sales',
       'occupation_ Tech-support', 'occupation_ Transport-moving',
       'income_ <=50K', 'income_ >50K'],
      dtype='object')

In [4]:
features = data_dummies.loc[:,"age":"occupation_ Transport-moving"]
X= features.values
y=data_dummies['income_ >50K']
print(X.shape,y.shape)

(32561, 44) (32561,)

In [5]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.35,random_state=0)

In [6]:
log=LogisticRegression()
log.fit(X_train,y_train)
log.score(X_train,y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.810952560952561

In [7]:
y_pred=log.predict(X_test)
log.score(X_test,y_pred)

1.0

In [8]:
display(data.head())

,age,workclass,education,gender,hours-per-week,occupation,income
0,39,State-gov,Bachelors,Male,40,Adm-clerical,<=50K
1,50,Self-emp-not-inc,Bachelors,Male,13,Exec-managerial,<=50K
2,38,Private,HS-grad,Male,40,Handlers-cleaners,<=50K
3,53,Private,11th,Male,40,Handlers-cleaners,<=50K
4,28,Private,Bachelors,Female,40,Prof-specialty,<=50K

In [9]:
from sklearn.preprocessing import StandardScaler
import pandas as pd

columns_to_scale = ['age','hours-per-week']
columns_categorical = ['workclass','education','gender','occupation','income']
# Initialize the StandardScaler
scaler = StandardScaler()

# Fit the scaler to the data and transform the data
scaled_data = scaler.fit_transform(data[['age','hours-per-week']])

# Convert the scaled data back to a DataFrame
scaled_df = pd.DataFrame(scaled_data,columns=columns_to_scale)
scaled_df[columns_categorical] = data[columns_categorical]

print("Original DataFrame:")
print(data)
print("\nScaled DataFrame:")
print(scaled_df)

Original DataFrame:
       age          workclass    education   gender  hours-per-week  \
0       39          State-gov    Bachelors     Male              40
1       50   Self-emp-not-inc    Bachelors     Male              13
2       38            Private      HS-grad     Male              40
3       53            Private         11th     Male              40
4       28            Private    Bachelors   Female              40
...    ...                ...          ...      ...             ...
32556   27            Private   Assoc-acdm   Female              38
32557   40            Private      HS-grad     Male              40
32558   58            Private      HS-grad   Female              40
32559   22            Private      HS-grad     Male              20
32560   52       Self-emp-inc      HS-grad   Female              40

               occupation  income
0            Adm-clerical   <=50K
1         Exec-managerial   <=50K
2       Handlers-cleaners   <=50K
3       Handlers-cleaners   <=50K
4          Prof-specialty   <=50K
...                   ...     ...
32556        Tech-support   <=50K
32557   Machine-op-inspct    >50K
32558        Adm-clerical   <=50K
32559        Adm-clerical   <=50K
32560     Exec-managerial    >50K

[32561 rows x 7 columns]

Scaled DataFrame:
            age  hours-per-week          workclass    education   gender  \
0      0.030671       -0.035429          State-gov    Bachelors     Male
1      0.837109       -2.222153   Self-emp-not-inc    Bachelors     Male
2     -0.042642       -0.035429            Private      HS-grad     Male
3      1.057047       -0.035429            Private         11th     Male
4     -0.775768       -0.035429            Private    Bachelors   Female
...         ...             ...                ...          ...      ...
32556 -0.849080       -0.197409            Private   Assoc-acdm   Female
32557  0.103983       -0.035429            Private      HS-grad     Male
32558  1.423610       -0.035429            Private      HS-grad   Female
32559 -1.215643       -1.655225            Private      HS-grad     Male
32560  0.983734       -0.035429       Self-emp-inc      HS-grad   Female

               occupation  income
0            Adm-clerical   <=50K
1         Exec-managerial   <=50K
2       Handlers-cleaners   <=50K
3       Handlers-cleaners   <=50K
4          Prof-specialty   <=50K
...                   ...     ...
32556        Tech-support   <=50K
32557   Machine-op-inspct    >50K
32558        Adm-clerical   <=50K
32559        Adm-clerical   <=50K
32560     Exec-managerial    >50K

[32561 rows x 7 columns]

In [ ]:
print(scaled_df)

            age  hours-per-week          workclass    education   gender  \
0      0.030671       -0.035429          State-gov    Bachelors     Male
1      0.837109       -2.222153   Self-emp-not-inc    Bachelors     Male
2     -0.042642       -0.035429            Private      HS-grad     Male
3      1.057047       -0.035429            Private         11th     Male
4     -0.775768       -0.035429            Private    Bachelors   Female
...         ...             ...                ...          ...      ...
32556 -0.849080       -0.197409            Private   Assoc-acdm   Female
32557  0.103983       -0.035429            Private      HS-grad     Male
32558  1.423610       -0.035429            Private      HS-grad   Female
32559 -1.215643       -1.655225            Private      HS-grad     Male
32560  0.983734       -0.035429       Self-emp-inc      HS-grad   Female

               occupation  income
0            Adm-clerical   <=50K
1         Exec-managerial   <=50K
2       Handlers-cleaners   <=50K
3       Handlers-cleaners   <=50K
4          Prof-specialty   <=50K
...                   ...     ...
32556        Tech-support   <=50K
32557   Machine-op-inspct    >50K
32558        Adm-clerical   <=50K
32559        Adm-clerical   <=50K
32560     Exec-managerial    >50K

[32561 rows x 7 columns]

In [12]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler

ct = ColumnTransformer([
    ('scaling', StandardScaler(), ['age', 'hours-per-week']),
    ('onehot', OneHotEncoder(sparse_output=False), ['workclass', 'education', 'gender', 'occupation'])
])

In [13]:
features = data.loc[:,"age":"occupation"]
X= features
y=data['income']
print(X.shape,y.shape)

(32561, 6) (32561,)

In [14]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.35,random_state=0)

In [15]:
# Fit the ColumnTransformer on the training data
ct.fit(X_train)

# Transform the training data
X_train_trans = ct.transform(X_train)
print(X_train_trans)

[[-1.36662402  0.20590528  0.         ...  0.          0.
   0.        ]
 [-0.48519666 -0.03816876  0.         ...  0.          0.
   0.        ]
 [-1.36662402 -0.03816876  0.         ...  0.          0.
   0.        ]
 ...
 [-1.14626718 -0.03816876  0.         ...  1.          0.
   0.        ]
 [ 0.46968297  0.3686213   0.         ...  0.          0.
   0.        ]
 [-0.99936262  0.61269534  0.         ...  0.          0.
   0.        ]]

In [16]:
X_train_trans.shape

(21164, 44)

In [17]:
from sklearn.linear_model import LogisticRegression

log=LogisticRegression()
log.fit(X_train_trans,y_train)
log.score(X_train_trans,y_train)

0.8127953127953128

In [18]:
X_test_trans = ct.transform(X_test)

In [19]:
y_pred=log.predict(X_test_trans)

In [20]:
log.score(X_test_trans,y_pred)

1.0